package com.mycompany.proyectorestaurante.Formularios;

import com.mycompany.proyectorestaurante.Menu;
import com.mycompany.proyectorestaurante.Pedido;
import com.mycompany.proyectorestaurante.PedidosEnCurso;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;

public class FormTomarPedido extends javax.swing.JFrame {

    ArrayList<String> textoResumenPedido = new ArrayList<>();
    private Pedido pedido = new Pedido();
    private PedidosEnCurso pedidosDia = new PedidosEnCurso();

    private String obtenerTextoPedido() {
        String texto = "";
        for (int i = 0; i < textoResumenPedido.size(); i++) {
            texto += (i+1) + textoResumenPedido.get(i);
        }
        return texto;
    }

    public FormTomarPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        totalPedidoText.setEditable(false);

        try {
            Menu menu = new Menu();
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("archivos\\menu.txt"));
            menu = (Menu) ois.readObject();
            menuText.setText(menu.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }

        resumenPedido.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        ingresarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreClienteText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumenPedido = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        platoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cantidadBox = new javax.swing.JComboBox<>();
        agregarPlato = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        numeroEliminarPedido = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totalPedidoText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        menuText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tomar Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        ingresarPedido.setText("Ingresar Pedido");
        ingresarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Cliente:");

        nombreClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Pedido:");

        resumenPedido.setColumns(20);
        resumenPedido.setForeground(new java.awt.Color(0, 0, 0));
        resumenPedido.setRows(5);
        resumenPedido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(resumenPedido);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Plato"));

        jLabel1.setText("Nro plato:");

        platoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platoTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Cant.");

        cantidadBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cantidadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadBoxActionPerformed(evt);
            }
        });

        agregarPlato.setText("Ok");
        agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platoText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(platoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarPlato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar del pedido"));

        jLabel5.setText("Nro plato(pedido):");

        numeroEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroEliminarPedidoActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel6.setText("Total:");

        totalPedidoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPedidoTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreClienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalPedidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreClienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volver)
                            .addComponent(ingresarPedido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPedidoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        menuText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void cantidadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadBoxActionPerformed

    private void platoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platoTextActionPerformed

    private void nombreClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteTextActionPerformed

    private void agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlatoActionPerformed
        try {
            String aux = platoText.getText();
            if (!aux.isEmpty()) {
                int numeroPlato = Integer.parseInt(platoText.getText());
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream("archivos\\menu.txt"));
                Menu menu = (Menu) ois.readObject();
                if (numeroPlato <= menu.getPlatos().size() && numeroPlato > 0) {
                    int i = 1;
                    for (Map.Entry<String, Double> entry : menu.getPlatos().entrySet()) {
                        if (i == numeroPlato) {
                            String plato = entry.getKey();
                            double precio = entry.getValue();
                            int cantidad = Integer.parseInt(cantidadBox.getSelectedItem().toString());
                            String linea = " " + plato + "   x" + cantidad + "    " + (precio * cantidad) + "\n";
                            String texto = "";
                            textoResumenPedido.add(linea);

                            resumenPedido.setText(obtenerTextoPedido());
                            //StringBuilder sb = new StringBuilder();
                            //sb.append(i + " " + plato + "   x" + cantidad + "    " + (precio*cantidad) + "\n");
                            //resumenPedido.append(i + plato + "   x" + cantidad + "  " + (precio * cantidad) + "\n");
                            double precioTotal = precio * cantidad;
                            precioTotal += pedido.getPrecioTotal();
                            totalPedidoText.setText(String.valueOf(precioTotal));

                            pedido.setPrecioTotal(precioTotal);
                            pedido.getPlatos().put(plato, cantidad);
                            platoText.setText("");
                            cantidadBox.setSelectedIndex(0);
                        }
                        i++;
                    }
                }
                ois.close();
            } else {
                JOptionPane.showMessageDialog(null, "Plato no seleccionado");
            }

        } catch (IOException | ClassNotFoundException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }

    }//GEN-LAST:event_agregarPlatoActionPerformed

    private void ingresarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarPedidoActionPerformed
        String nombreCli = nombreClienteText.getText();
        String aux = resumenPedido.getText();

        if (!nombreCli.isEmpty() && !aux.isEmpty()) {
            //FALTA CODIGO
            pedido.setResumenPedido(resumenPedido.getText());
            pedido.setNombreCliente(nombreCli);
            pedido.setFecha(new Date());
            try {
                File file = new File("archivos\\pedidosActuales.txt");
                if (file.length() != 0) {
                    ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));
                    pedidosDia = (PedidosEnCurso) ois.readObject();
                    pedidosDia.agregarPedido(pedido);
                } else {
                    pedidosDia.agregarPedido(pedido);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            }

            platoText.setText("");
            resumenPedido.setText("");
            nombreClienteText.setText("");
            cantidadBox.setSelectedIndex(0);

            //NO SE GUARDA EN EL REPOSITORIO XQ TODAVIA PUEDE CANCELARSE
            pedido.setPrecioTotal(0);

            JOptionPane.showMessageDialog(null, "Pedido en curso agregado correctamente.");

        } else if (nombreCli.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del cliente.");
        } else if (aux.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregar plato al pedido.");
        }
    }//GEN-LAST:event_ingresarPedidoActionPerformed

    private void numeroEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroEliminarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroEliminarPedidoActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        String numero = numeroEliminarPedido.getText();
        int numeroEntero = Integer.parseInt(numero);

        if (!numero.isEmpty() && numeroEntero > 0 && numeroEntero <= textoResumenPedido.size()) {
            textoResumenPedido.remove(numeroEntero-1);
            
            String plato = "";  
            int i = 1;
            for (Map.Entry<String, Integer> entry : pedido.getPlatos().entrySet()) {
                if (i == numeroEntero) {
                    plato = entry.getKey();
                    
                }
                i++;
            }
            pedido.getPlatos().remove(plato);
            resumenPedido.setText(obtenerTextoPedido());
            JOptionPane.showMessageDialog(null, "Plato eliminado del pedido correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void totalPedidoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPedidoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPedidoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTomarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTomarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTomarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTomarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTomarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPlato;
    private javax.swing.JComboBox<String> cantidadBox;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton ingresarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuText;
    private javax.swing.JTextField nombreClienteText;
    private javax.swing.JTextField numeroEliminarPedido;
    private javax.swing.JTextField platoText;
    private javax.swing.JTextArea resumenPedido;
    private javax.swing.JTextField totalPedidoText;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
