package com.mycompany.proyectorestaurante.Formularios;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FormEmpleado extends javax.swing.JFrame {

    public FormEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tomarPedidos = new javax.swing.JButton();
        pedidosEnCurso = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tomarPedidos.setText("Tomar Pedidos");
        tomarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarPedidosActionPerformed(evt);
            }
        });

        pedidosEnCurso.setText("Pedidos en Curso");
        pedidosEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosEnCursoActionPerformed(evt);
            }
        });

        volverButton.setText("Cambiar de usuario");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volverButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pedidosEnCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(tomarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tomarPedidos)
                .addGap(18, 18, 18)
                .addComponent(pedidosEnCurso)
                .addGap(27, 27, 27)
                .addComponent(volverButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tomarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarPedidosActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    FormTomarPedido tomarPedido = new FormTomarPedido();
    
        tomarPedido.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            setVisible(true); // Hacer visible el JFrame anterior cuando se cierre tomarPedido
        }
    });
    
    tomarPedido.setVisible(true);
        
    }//GEN-LAST:event_tomarPedidosActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void pedidosEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosEnCursoActionPerformed
        // TODO add your handling code here:
        setVisible(false);  
        FormPedidosEnCurso pedidosActuales = new FormPedidosEnCurso();
        pedidosActuales.setVisible(true);
        
        pedidosActuales.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                setVisible(true);
            }
        });
    }//GEN-LAST:event_pedidosEnCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pedidosEnCurso;
    private javax.swing.JButton tomarPedidos;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
