/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectorestaurante.Formularios;

import com.mycompany.proyectorestaurante.Pedido;
import com.mycompany.proyectorestaurante.PedidosEnCurso;
import com.mycompany.proyectorestaurante.Repositorio;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class PanelPedido extends javax.swing.JPanel {

    public PanelPedido() {
        initComponents();
        cancelarButton.setForeground(Color.red);
        pedidoCompletadoButton.setForeground(new Color(23, 144, 24));
        setVisible(true);
    }
    
    public void setActionEvent() {
    PanelPedido self = this; // Guardar referencia al panelPedido actual

    cancelarButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("Boton presionado");
            JPanel parent = (JPanel) self.getParent();
            parent.remove(self);
            parent.revalidate();
            parent.repaint();
        }
    });
    
    pedidoCompletadoButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("Boton presionado");
            JPanel parent = (JPanel) self.getParent();
            parent.remove(self);
            parent.revalidate();
            parent.repaint();
        }
    });
    
}

   


    public JLabel getPrecioTotalLabel() {
        return precioTotalLabel;
    }

    public void setPrecioTotalLabel(Double precioTotalLabel) {
        this.precioTotalLabel.setText(String.valueOf(precioTotalLabel));
    }

    public JLabel getDescripcionPedido() {
        return descripcionPedido;
    }

    public void setDescripcionPedido(String resumenPedido) {
        this.descripcionPedido.setText(resumenPedido);
    }

    public JLabel getHoraPedido() {
        return horaPedido;
    }

    public void setHoraPedido(Date horaPedido) {
        SimpleDateFormat aux = new SimpleDateFormat("HH:mm:ss");
        String formatoHora = aux.format(horaPedido);
        this.horaPedido.setText(formatoHora);
    }

    public JLabel getNombreCliente() {
        return nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente.setText(nombreCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        horaPedido = new javax.swing.JLabel();
        descripcionPedido = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        pedidoCompletadoButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        precioTotalLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("NOMBRE:");

        nombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreCliente.setText("texto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("DESCRIPCION:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("HORA:");

        horaPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horaPedido.setText("texto");

        descripcionPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcionPedido.setText("texto");
        descripcionPedido.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cancelarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 10)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        pedidoCompletadoButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        pedidoCompletadoButton.setText("Pedido Completado");
        pedidoCompletadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoCompletadoButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("MONTO:");

        precioTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioTotalLabel.setText("texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descripcionPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cancelarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pedidoCompletadoButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horaPedido))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pedidoCompletadoButton)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //EL BOTON ESTA CONFIGURADO EN TOMAR MAS ARRIBA DE ESTA CLASE
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        PedidosEnCurso pec = new PedidosEnCurso();
        try{
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("archivos\\pedidosActuales.txt"));
            pec = (PedidosEnCurso) ois.readObject();
            ois.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
        
        for (int i = 0; i < pec.getPedidosActuales().size(); i++) {
            Pedido pedidoAux = pec.getPedidosActuales().get(i);
            if(pedidoAux.getNombreCliente().equals(nombreCliente.getText()) && pedidoAux.getPrecioTotal() == Double.parseDouble(precioTotalLabel.getText())){
                System.out.println("ENTRO ELIMINAR PEDIDO EN CURSO");
                pec.getPedidosActuales().remove(i);
            }
        }
        pec.guardarPedidosEnCurso();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void pedidoCompletadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoCompletadoButtonActionPerformed
        Pedido pedido = new Pedido();
        pedido.setNombreCliente(nombreCliente.getText());
        pedido.setPrecioTotal(Double.parseDouble(precioTotalLabel.getText()));

        Calendar calendario = Calendar.getInstance();
        String horaString = horaPedido.getText();
        LocalTime hora = LocalTime.parse(horaString);

        calendario.set(Calendar.HOUR_OF_DAY, hora.getHour());
        calendario.set(Calendar.MINUTE, hora.getMinute());
        calendario.set(Calendar.SECOND, hora.getSecond());

        Date fechaActualConHora = calendario.getTime();

        pedido.setFecha(fechaActualConHora);

        //Convertir el String de la descripcion de todos los platos a un LinkedHashMap
        System.out.println(descripcionPedido.getText());
        String textoSinHtml = descripcionPedido.getText().replaceAll("\\<.*?\\>", "");
        String[] filas = textoSinHtml.split("\\n");

        Map<String, Integer> platos = new LinkedHashMap<>();
        //CORREGIR ESTA PARTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA
        Pattern pattern = Pattern.compile("([^\\.]+)\\.+?(\\d+)");
        Matcher matcher = pattern.matcher(descripcionPedido.getText());
        while (matcher.find()) {
            String comida = matcher.group(1).replaceAll("\\<.*?\\>", "").trim();
            int numero = Integer.parseInt(matcher.group(2));

            platos.put(comida, numero);
        }

        pedido.setPlatos(platos);
        
        PedidosEnCurso pec = new PedidosEnCurso();
        try{
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("archivos\\pedidosActuales.txt"));
            pec = (PedidosEnCurso) ois.readObject();
            ois.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
        
        for (int i = 0; i < pec.getPedidosActuales().size(); i++) {
            Pedido pedidoAux = pec.getPedidosActuales().get(i);
            if(pedidoAux.getNombreCliente().equals(nombreCliente.getText()) && pedidoAux.getPrecioTotal() == Double.parseDouble(precioTotalLabel.getText())){
                System.out.println("ENTRO ELIMINAR PEDIDO EN CURSO");
                pec.getPedidosActuales().remove(i);
            }
        }
        pec.guardarPedidosEnCurso();
        
        Repositorio repositorio = Repositorio.cargarRepositorio();
        repositorio.registrarPedido(pedido, new Date());
        repositorio.imprimirPedidosPorDia();

    }//GEN-LAST:event_pedidoCompletadoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel descripcionPedido;
    private javax.swing.JLabel horaPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JButton pedidoCompletadoButton;
    private javax.swing.JLabel precioTotalLabel;
    // End of variables declaration//GEN-END:variables
}
